apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pv-mounter
spec:
  version: "v0.0.6"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/fenio/pv-mounter/releases/download/v0.0.6/pv-mounter_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./pv-mounter"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pv-mounter"
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/fenio/pv-mounter/releases/download/v0.0.6/pv-mounter_linux_arm64.tar.gz
    sha256: ""
    files:
    - from: "./pv-mounter"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pv-mounter"

  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/fenio/pv-mounter/releases/download/v0.0.6/pv-mounter_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./pv-mounter"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pv-mounter"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/fenio/pv-mounter/releases/download/v0.0.6/pv-mounter_darwin_arm64.tar.gz
    sha256: ""
    files:
    - from: "./pv-mounter"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pv-mounter"

  shortDescription: Mount PVC locally using sshfs
  homepage: https://github.com/fenio/pv-mounter
  description: |
    Plugin that allows to mount PVC locally using sshfs
